234 토큰 중복 발급
42Where/where42_back_v2 pull request #249
Opened 2024-12-30 07:28 UTC by parksooo

### Token 관련 redis 사용하는 것으로 변경

- 재발급 시 intraId를 통해 발급, 인트라 아이디를 통한 refreshToken 조회
- 맴버 탈퇴 및 로그아웃 시 accessToken 블랙리스트에 저장
- 사용자 인가 시, 블랙리스트에 accessToken의 저장 여부 확인하여 진행

2025-01-01 12:56 UTC, hanjjong requested changes
전체적인 토큰 관리 흐름은 잘 구현된거 같은데욥??? ㅎㅎ 그리고 회원가입 로직을 수정하고 나서 멤버 탈퇴하고 원래 있던 토큰으로 요청하니까 브라우저에서 무한루프로 api 요청 난사 하더라구요 블랙리스트 얼른 적용하면 좋을 것 같습니다 👍

2025-01-01 12:56 UTC, hanjjong commented on src/main/java/kr/where/backend/auth/oauth2login/OAuth2SuccessHandler.java
> +                                .fromUriString("https://dev.where42.kr")
이거 도메인 바꾸는게 너무 귀찮아서 환경변수로 빼놓을려구용 어떠신가욤?

2025-01-01 12:56 UTC, hanjjong commented on src/main/java/kr/where/backend/jwt/swagger/JwtApiDocs.java
받는 requestBody도 명시해주면 좋을 것 같아요. 프론트 ios 분들이 알아보기 쉬워야 할것같아요~

2025-01-01 12:56 UTC, hanjjong commented on src/main/java/kr/where/backend/logout/LogoutController.java
>      }
로그아웃도 스웨거 작성 해주시면 감사하겠습니당

2025-01-01 12:56 UTC, hanjjong commented on src/test/java/kr/where/backend/redisToken/ApiTestUsingRedisServiceTest.java
> +    }
오호 컨트롤러 테스트하기에 딱 좋네요 유사 postman~!

2025-01-01 12:56 UTC, hanjjong commented on src/test/java/kr/where/backend/redisToken/ApiTestUsingRedisServiceTest.java
> +        Member m = memberService.createAgreeMember(cadetPrivacy, hane);
memberService.createAgreeMember(cadetPrivacy, hane);
그냥 이렇게 작성해버리기? 어떤가요 변수명도 짓기 어려운데

2025-01-01 12:56 UTC, hanjjong commented on src/test/java/kr/where/backend/redisToken/RedisTokenServiceTest.java
> +}
저희 테스트 코드를 실행할때 쓰는 데이터베이스는 h2같은 인메모리 디비를 쓰잖아요? 레디스는 어떻게 테스트 되는걸까요? 아마 테스트용 레디스가 따로 올라가는 거겟죠?

2025-01-01 12:56 UTC, hanjjong commented on src/main/java/kr/where/backend/configuration/RedisConfig.java
> +}
이거보고 하나도 모르겠는걸 보니 레디스 자체도 뭔지 제대로 공부해봐야겟네요.ㅎㅎㅎ

2025-01-01 12:56 UTC, hanjjong commented on src/main/java/kr/where/backend/redisToken/RedisTokenService.java
> +    }
음 만료된 토큰은 토큰이 키 id가 밸류~ 오퀘이 좋숩니다

2025-01-01 12:56 UTC, hanjjong commented on src/main/java/kr/where/backend/redisToken/RedisTokenService.java
> +public class RedisTokenService {
흠 근데 레디스 서비스는 트랜잭션을 안걸어줘도 될까요? 걸어줄수 있다면 걸어줘야 할것 같습니다!

2025-01-01 16:13 UTC, leeesooha commented on src/main/java/kr/where/backend/auth/oauth2login/OAuth2FailureHandler.java
> +        response.sendRedirect("https://dev.where42.kr/login-fail");
앗 dev가 적혀버렸네욤

2025-01-01 16:15 UTC, leeesooha commented on src/main/java/kr/where/backend/auth/oauth2login/OAuth2SuccessHandler.java
> +            redisTokenService.saveRefreshToken(member.getIntraId().toString(), refreshToken);
오 이제 refresh 토큰을 쿠키에 저장하지 않고, 레디스에 저장하게 되는 건가요?

2025-01-01 16:21 UTC, leeesooha commented on src/main/java/kr/where/backend/configuration/RedisConfig.java
> +}
RedisTemplate이 "defaultRedisTemplate()", "redisTemplate()"두 가지가 있는데 어떤 이윤지 알 수 있을까요..?

2025-01-01 16:29 UTC, leeesooha commented on src/test/java/kr/where/backend/redisToken/ApiTestUsingRedisServiceTest.java
> +
오 api에 대한 요청을 테스트 코드에서 하는 방법도 있네요! 너무 유용한 좋은 방법인것 같습니다!

2025-01-01 16:39 UTC, leeesooha commented
레디스 어려우셨을텐데 너무 멋지게 잘 된것같습니다! 레디스사용 코드를 처음보는데 가독성 좋아 잘 읽히는 코드인것 같습니다 많이 배워갑니다!

2025-01-02 07:36 UTC, parksooo commented on src/main/java/kr/where/backend/auth/filter/JwtExceptionFilter.java
> +            SecurityContextHolder.clearContext();
음 그런건 아닌데, 아마 한번 등록되면 전역적으로 저장이 되어서, 인가 상황중에 에러가 난다면 clear를 하는게 좋다고 하더라구요!

2025-01-02 07:37 UTC, parksooo commented on src/main/java/kr/where/backend/auth/oauth2login/OAuth2SuccessHandler.java
> +                                .fromUriString("https://dev.where42.kr")
아 너무 좋습니다! 제가 이거 까먹었네요 ㅠ

2025-01-02 07:37 UTC, parksooo commented on src/main/java/kr/where/backend/jwt/swagger/JwtApiDocs.java
request body를 명시한다는게 어떤 말씀인가여?

2025-01-02 07:38 UTC, parksooo commented on src/main/java/kr/where/backend/logout/LogoutController.java
>      }
넵 ~ 만들어볼께요

2025-01-02 07:38 UTC, parksooo commented on src/test/java/kr/where/backend/redisToken/ApiTestUsingRedisServiceTest.java
> +    }
네네 한번 다음에 api test해보시죠~ 이거 부하테스트도 가능할거에요~

2025-01-02 07:38 UTC, parksooo commented on src/test/java/kr/where/backend/redisToken/ApiTestUsingRedisServiceTest.java
> +        Member m = memberService.createAgreeMember(cadetPrivacy, hane);
member를 사용하지 않으니까 그냥 변수 받지 말자?

2025-01-02 07:39 UTC, parksooo commented on src/test/java/kr/where/backend/redisToken/RedisTokenServiceTest.java
> +}
테스트용 레디스는 없어여!
저희는 외부 레디스와 연동해서 사용하는 것이여서, 저는 제 로컬에 있는 redis와 연결해서 사용했습니다

2025-01-02 07:40 UTC, hanjjong commented on src/main/java/kr/where/backend/jwt/swagger/JwtApiDocs.java
스웨거에 requestBody가 빠져있는것 같아용

2025-01-02 07:40 UTC, hanjjong commented on src/test/java/kr/where/backend/redisToken/ApiTestUsingRedisServiceTest.java
> +        Member m = memberService.createAgreeMember(cadetPrivacy, hane);
네네 맞숨다

2025-01-02 07:44 UTC, parksooo commented on src/main/java/kr/where/backend/configuration/RedisConfig.java
> +}
제가 알기로는 redis 관련 설정을 해주어야, springboot에서 가동이 된다고 알고 있습니다.
redis도 종류가 꽤 있어서, 저희는 그냥 위의 코드에서 보이다 싶이 String, Object로 생성하는 template를 사용하고
키 벨류 값을 직렬화해서 redis에 저장하는 흐름입니다

만약, 객체를 사용해서 redis에 {key, 객체} 이렇게 저장할 때도 있으니, config를 변경해서 사용하면 될거같아요!

2025-01-02 07:44 UTC, parksooo commented on src/main/java/kr/where/backend/redisToken/RedisTokenService.java
> +    }
굿굿

2025-01-02 07:47 UTC, parksooo commented on src/main/java/kr/where/backend/redisToken/RedisTokenService.java
> +public class RedisTokenService {
음 transactional 어노테이션은 springboot에 연결된 ORM에 대해서 작용하는 것 같습니다.
entitymanager가 persist하고 하는 과정에서 transaction 생명주기를 관리할때 사용하는 것인데,
Redis는 config에서 설정한것 처럼, key value에 대한 값을 직렬화해서 저장하고, redis 특성상 싱글스레드여서 생명주기는 ttl로 하는것 같습니다

2025-01-02 07:48 UTC, parksooo commented on src/main/java/kr/where/backend/auth/oauth2login/OAuth2FailureHandler.java
> +        response.sendRedirect("https://dev.where42.kr/login-fail");
네네 변경할게여~

2025-01-02 07:48 UTC, parksooo commented on src/main/java/kr/where/backend/auth/oauth2login/OAuth2SuccessHandler.java
> +            redisTokenService.saveRefreshToken(member.getIntraId().toString(), refreshToken);
넵 그렇습니다

2025-01-02 07:53 UTC, parksooo commented on src/main/java/kr/where/backend/configuration/RedisConfig.java
> +}
오 근데 잘 되네여? 없어도 저번에는 없으면 에러가 났는데
고쳐서 올려놓을께여

2025-01-02 07:54 UTC, parksooo commented on src/test/java/kr/where/backend/redisToken/ApiTestUsingRedisServiceTest.java
> +
네네 한번 시도해보세요

2025-01-02 08:00 UTC, parksooo commented on src/main/java/kr/where/backend/jwt/swagger/JwtApiDocs.java
오키오키

2025-01-02 08:05 UTC, hanjjong commented on src/main/java/kr/where/backend/redisToken/RedisTokenService.java
> +public class RedisTokenService {
결국 레디스도 코드 실행중간에 터질 수도 있을것 같아서 트랜잭션 어노테이션처럼 롤백을 해주는 무언가가 있어야 하지 않을까라는 생각이 들었습니다. 
그래서 찾아보니  @transactional로도 레디스 롤백이 가능한거 같은데 한번 확인해주시겠어욤? 추가적으로 config에 트랜잭션 옵션을 켜주어야 하는 것 같습니다.
https://sabarada.tistory.com/178

2025-01-02 08:05 UTC, parksooo commented on src/test/java/kr/where/backend/redisToken/RedisTokenServiceTest.java
> +}
아마 따로 지정하지 않으면 local 메모리를 사용할거같아요

2025-01-02 08:06 UTC, parksooo commented
> 전체적인 토큰 관리 흐름은 잘 구현된거 같은데욥??? ㅎㅎ 그리고 회원가입 로직을 수정하고 나서 멤버 탈퇴하고 원래 있던 토큰으로 요청하니까 브라우저에서 무한루프로 api 요청 난사 하더라구요 블랙리스트 얼른 적용하면 좋을 것 같습니다 👍

좋습니다 수정해서 올려보죠!

2025-01-02 08:30 UTC, parksooo commented on src/main/java/kr/where/backend/redisToken/RedisTokenService.java
> +public class RedisTokenService {
음 저는 중간에 터진다. 라는 상황이 있을까 고민이 됩니다.
만약 중간에 터지는 상황이면, redis의 docker가 내려가는 상황 말고는 생각이 나지 않네요...
지금 저희가 사용하는 redis 기능은 로그아웃, 회원 탈퇴, reiusse입니다.
redis의 동작과정은, multi 환경에서 큐에 모든 명령어를 쌓아놓고 한번에 처리는 합니다
트랜젝션이 필요한 상황은 data의 원자성을 보장하는 것리아고 생각합니다.

하지만 지금 저희가 사용하는 메서드에서는 원자성이 보장이 된다고 생각합니다.
외부 api를 통해 원자성이 변경되거나 오염되는 경우는 없을거 같네요....

redis transaction을 사용하는 경우는 사실 db의 data를 캐시화해서 사용할때, db와 redis의 정보의 원자성을 보장하려 할때 사용하는 것 같습니다.
즉, 원자성과 동시성을 보장할때 사용하는게 적절해 보인다는 의견입니다!

저희 서비스는 원자성과 동시성 보장보다는 토큰 관리에서 사용되다 보니, 트랜잭션를 사용한다면 약간의 resource 낭비라고 생각이 들어요

2025-01-02 08:51 UTC, hanjjong commented on src/main/java/kr/where/backend/redisToken/RedisTokenService.java
> +public class RedisTokenService {
무슨 말인지 이해했습니당 근데 중간에 터진다라는게 RedisTokenService에 있는 코드를 실행하는 것뿐만 아니라 
레디스 서비스를 이용하는 모든 서비스 코드들이 중간에 터질수도 있지 않을까? 라는 의미도 있습니다.
```
	final String accessToken = jwtService.extractToken(request).orElse(null);
		redisTokenService.invalidateToken(accessToken, authUser.getIntraId().toString());
		memberRepository.delete(member);
```
예를 들면 요건 로그아웃 코드인데 delete하다가 원인 모를 예외나 에러가 터질수도 있지 않을까 싶은데 이럴때 레디스도 롤백이 되어야하는 것 아닐까욤..? 
물론 서비스 동작에는 큰차이는 없겟지만~ 레디스와 디비 사이의 원자성도 보장해주어야 하지 않을까?! 라는 생각인데 어떠신가요?

2025-01-02 08:57 UTC, parksooo commented on src/main/java/kr/where/backend/redisToken/RedisTokenService.java
> +public class RedisTokenService {
레디스와 디비 사이의 원자성의 관계는 지금의 서비스에서는 적용할 수 없지 않을까요?
토큰을 postgres에 저장해 놓지 않는 이상, 토큰 정보의 원자성은 오롯이 redis의 몫이라고 생각합니다!

만약 종민님이 말씀하신 상황에서 delete 하다가 원인 모를 예외가 터지면, 다시 로그인해서 탈퇴를 진행하는 것이 더 바람직하다고 생각합니다!
어는 상황이더라도 무효화한 토큰을 다시 유효화하게 하는것이 맞는 방식일까 라는 생각이 들어용

2025-01-02 10:57 UTC, leeesooha commented on src/main/java/kr/where/backend/configuration/RedisConfig.java
> +}
엇 고쳐야 할게 있는건가요..? 답변이해를 못했습니다..

2025-01-02 13:09 UTC, hanjjong commented on src/main/java/kr/where/backend/redisToken/RedisTokenService.java
> +public class RedisTokenService {
> 디비에 member가 삭제되지 않고, redis의 accessToken이 무효화된다는 과정을 원자성이라고 말씀하신걸까요? 
네네 단어 선택을 잘못했네욤..ㅎㅎ 원자성보단 정합성이 더 맞을 것 같습니다. 
여튼 저는 디비에는 남아 있는데 레디스에서는 토큰 만료시켜 버리는 뭔가 모순되는 상황을 말씀드린거긴 합니당

수환님 말씀대로 다시 로그인 하게해서 다시 탈퇴 진행시키는 방법도 괜찮은 것 같아여!
그럼 혹쉬 jpa 메서드 실행 후에 redisService실행시키는 건 어떨까요? 
롤백시킬 필요도 없이 마지막에!

변경 전 
```
final String accessToken = jwtService.extractToken(request).orElse(null);
redisTokenService.invalidateToken(accessToken, authUser.getIntraId().toString());
memberRepository.delete(member);
```


변경 후
```
final String accessToken = jwtService.extractToken(request).orElse(null);
memberRepository.delete(member);
redisTokenService.invalidateToken(accessToken, authUser.getIntraId().toString());
```

2025-01-03 03:28 UTC, parksooo commented on src/main/java/kr/where/backend/redisToken/RedisTokenService.java
> +public class RedisTokenService {
그리고 검색 기능할때, 저희가 transactional을 써야하니 그때 고민해보는걸로 하시죠!!

2025-01-03 03:28 UTC, parksooo commented on src/main/java/kr/where/backend/configuration/RedisConfig.java
> +}
아뇨아뇨 중복되서 하나를 지웠습니당

2025-01-05 05:32 UTC, merged